# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toplog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 518)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 631, 181))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.infoTab = QtWidgets.QWidget()
        self.infoTab.setObjectName("infoTab")
        self.infoText = QtWidgets.QTextBrowser(self.infoTab)
        self.infoText.setGeometry(QtCore.QRect(0, 0, 621, 151))
        self.infoText.setObjectName("infoText")
        self.tabWidget.addTab(self.infoTab, "")
        self.debugTab = QtWidgets.QWidget()
        self.debugTab.setObjectName("debugTab")
        self.debugText = QtWidgets.QTextBrowser(self.debugTab)
        self.debugText.setGeometry(QtCore.QRect(0, 0, 631, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.debugText.sizePolicy().hasHeightForWidth())
        self.debugText.setSizePolicy(sizePolicy)
        self.debugText.setObjectName("debugText")
        self.tabWidget.addTab(self.debugTab, "")
        self.errorTab = QtWidgets.QWidget()
        self.errorTab.setObjectName("errorTab")
        self.errorText = QtWidgets.QTextBrowser(self.errorTab)
        self.errorText.setGeometry(QtCore.QRect(0, 0, 631, 151))
        self.errorText.setObjectName("errorText")
        self.tabWidget.addTab(self.errorTab, "")
        self.speedBar = QtWidgets.QProgressBar(self.centralwidget)
        self.speedBar.setGeometry(QtCore.QRect(100, 220, 251, 23))
        self.speedBar.setProperty("value", 24)
        self.speedBar.setObjectName("speedBar")
        self.speedLabel = QtWidgets.QLabel(self.centralwidget)
        self.speedLabel.setGeometry(QtCore.QRect(0, 220, 101, 21))
        self.speedLabel.setObjectName("speedLabel")
        self.connectionBar = QtWidgets.QProgressBar(self.centralwidget)
        self.connectionBar.setGeometry(QtCore.QRect(100, 250, 251, 23))
        self.connectionBar.setProperty("value", 24)
        self.connectionBar.setObjectName("connectionBar")
        self.strengthLabel = QtWidgets.QLabel(self.centralwidget)
        self.strengthLabel.setGeometry(QtCore.QRect(0, 250, 81, 21))
        self.strengthLabel.setObjectName("strengthLabel")
        self.navigationButton = QtWidgets.QPushButton(self.centralwidget)
        self.navigationButton.setGeometry(QtCore.QRect(10, 290, 101, 31))
        self.navigationButton.setAutoFillBackground(False)
        self.navigationButton.setCheckable(False)
        self.navigationButton.setAutoDefault(False)
        self.navigationButton.setDefault(False)
        self.navigationButton.setFlat(False)
        self.navigationButton.setObjectName("navigationButton")
        self.armButton = QtWidgets.QPushButton(self.centralwidget)
        self.armButton.setGeometry(QtCore.QRect(10, 330, 101, 31))
        self.armButton.setObjectName("armButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(380, 300, 261, 191))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.batteryBar1 = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.batteryBar1.setProperty("value", 24)
        self.batteryBar1.setOrientation(QtCore.Qt.Vertical)
        self.batteryBar1.setObjectName("batteryBar1")
        self.horizontalLayout.addWidget(self.batteryBar1)
        self.batteryBar2 = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.batteryBar2.setProperty("value", 24)
        self.batteryBar2.setOrientation(QtCore.Qt.Vertical)
        self.batteryBar2.setObjectName("batteryBar2")
        self.horizontalLayout.addWidget(self.batteryBar2)
        self.batteryBar3 = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.batteryBar3.setProperty("value", 24)
        self.batteryBar3.setOrientation(QtCore.Qt.Vertical)
        self.batteryBar3.setObjectName("batteryBar3")
        self.horizontalLayout.addWidget(self.batteryBar3)
        self.batteryBar4 = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.batteryBar4.setProperty("value", 24)
        self.batteryBar4.setOrientation(QtCore.Qt.Vertical)
        self.batteryBar4.setObjectName("batteryBar4")
        self.horizontalLayout.addWidget(self.batteryBar4)
        self.batteryBar5 = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.batteryBar5.setProperty("value", 24)
        self.batteryBar5.setOrientation(QtCore.Qt.Vertical)
        self.batteryBar5.setObjectName("batteryBar5")
        self.horizontalLayout.addWidget(self.batteryBar5)
        self.batteryBar6 = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.batteryBar6.setProperty("value", 24)
        self.batteryBar6.setOrientation(QtCore.Qt.Vertical)
        self.batteryBar6.setObjectName("batteryBar6")
        self.horizontalLayout.addWidget(self.batteryBar6)
        self.batteryLabel = QtWidgets.QLabel(self.centralwidget)
        self.batteryLabel.setGeometry(QtCore.QRect(380, 280, 121, 17))
        self.batteryLabel.setObjectName("batteryLabel")
        self.imuButton = QtWidgets.QPushButton(self.centralwidget)
        self.imuButton.setGeometry(QtCore.QRect(130, 290, 101, 31))
        self.imuButton.setAutoFillBackground(False)
        self.imuButton.setCheckable(False)
        self.imuButton.setAutoDefault(False)
        self.imuButton.setDefault(False)
        self.imuButton.setFlat(False)
        self.imuButton.setObjectName("imuButton")
        self.gpsButton = QtWidgets.QPushButton(self.centralwidget)
        self.gpsButton.setGeometry(QtCore.QRect(130, 330, 101, 31))
        self.gpsButton.setObjectName("gpsButton")
        self.sensor1Button = QtWidgets.QPushButton(self.centralwidget)
        self.sensor1Button.setGeometry(QtCore.QRect(250, 290, 101, 31))
        self.sensor1Button.setAutoFillBackground(False)
        self.sensor1Button.setCheckable(False)
        self.sensor1Button.setAutoDefault(False)
        self.sensor1Button.setDefault(False)
        self.sensor1Button.setFlat(False)
        self.sensor1Button.setObjectName("sensor1Button")
        self.sensor2Button = QtWidgets.QPushButton(self.centralwidget)
        self.sensor2Button.setGeometry(QtCore.QRect(250, 330, 101, 31))
        self.sensor2Button.setObjectName("sensor2Button")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 400, 101, 25))
        self.comboBox.setObjectName("comboBox")
        self.roverIPText = QtWidgets.QLineEdit(self.centralwidget)
        self.roverIPText.setGeometry(QtCore.QRect(130, 400, 101, 25))
        self.roverIPText.setObjectName("roverIPText")
        self.killButton = QtWidgets.QPushButton(self.centralwidget)
        self.killButton.setGeometry(QtCore.QRect(400, 220, 221, 51))
        self.killButton.setObjectName("killButton")
        self.setIPButton = QtWidgets.QPushButton(self.centralwidget)
        self.setIPButton.setGeometry(QtCore.QRect(250, 400, 101, 25))
        self.setIPButton.setObjectName("setIPButton")
        self.imuIPText = QtWidgets.QLineEdit(self.centralwidget)
        self.imuIPText.setGeometry(QtCore.QRect(130, 400, 101, 25))
        self.imuIPText.setObjectName("imuIPText")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.infoTab), _translate("MainWindow", "Info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.debugTab), _translate("MainWindow", "Debug"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.errorTab), _translate("MainWindow", "Error"))
        self.speedBar.setFormat(_translate("MainWindow", "%p%"))
        self.speedLabel.setText(_translate("MainWindow", "ROVER SPEED"))
        self.strengthLabel.setText(_translate("MainWindow", "STRENGTH"))
        self.navigationButton.setText(_translate("MainWindow", "NAVIGATION"))
        self.armButton.setText(_translate("MainWindow", "ARM"))
        self.batteryBar1.setFormat(_translate("MainWindow", "%s%"))
        self.batteryLabel.setText(_translate("MainWindow", "BATTERY STATUS"))
        self.imuButton.setText(_translate("MainWindow", "IMU"))
        self.gpsButton.setText(_translate("MainWindow", "GPS "))
        self.sensor1Button.setText(_translate("MainWindow", "SENSOR 1"))
        self.sensor2Button.setText(_translate("MainWindow", "SENSOR 2"))
        self.killButton.setText(_translate("MainWindow", "KILL"))
        self.setIPButton.setText(_translate("MainWindow", "SET IP"))

